// Exercise categories
export const CATEGORIES = {
  BOXING: 'Boxing',
  KICKBOXING: 'Kickboxing',
  MUAY_THAI: 'Muay Thai',
  CALISTHENICS: 'Calisthenics',
  HIIT: 'HIIT',
  WEIGHTLIFTING: 'Weightlifting'
};

export const BODY_AREAS = {
  FULL_BODY: 'Full Body',
  UPPER_BODY: 'Upper Body',
  LOWER_BODY: 'Lower Body',
  CORE: 'Core',
  CARDIO: 'Cardio',
  ARMS: 'Arms',
  LEGS: 'Legs',
  CHEST: 'Chest',
  BACK: 'Back',
  SHOULDERS: 'Shoulders'
};

export const workoutData = [
  // Boxing Exercises (25)
  { id: 1, title: 'Boxing Fundamentals', category: CATEGORIES.BOXING, level: 'Beginner', videoId: 'dQw4w9WgXcQ', bodyArea: BODY_AREAS.UPPER_BODY, duration: 20 },
  { id: 2, title: 'Heavy Bag Training', category: CATEGORIES.BOXING, level: 'Intermediate', videoId: '3JZ_D3ELwOQ', bodyArea: BODY_AREAS.FULL_BODY, duration: 30 },
  { id: 3, title: 'Speed Bag Workout', category: CATEGORIES.BOXING, level: 'Intermediate', videoId: '2vjPBrBU-TM', bodyArea: BODY_AREAS.ARMS, duration: 15 },
  { id: 4, title: 'Boxing Combos & Footwork', category: CATEGORIES.BOXING, level: 'Advanced', videoId: 'kJQP7kiw5Fk', bodyArea: BODY_AREAS.FULL_BODY, duration: 25 },
  { id: 5, title: 'Boxing Conditioning', category: CATEGORIES.BOXING, level: 'Advanced', videoId: 'ZZ5LpwO-An4', bodyArea: BODY_AREAS.CARDIO, duration: 35 },
  { id: 6, title: 'Jab Cross Fundamentals', category: CATEGORIES.BOXING, level: 'Beginner', videoId: 'IODxDxX7oi4', bodyArea: BODY_AREAS.ARMS, duration: 15 },
  { id: 7, title: 'Hook & Uppercut Mastery', category: CATEGORIES.BOXING, level: 'Intermediate', videoId: 'eGo4IYlbE5g', bodyArea: BODY_AREAS.UPPER_BODY, duration: 20 },
  { id: 8, title: 'Shadow Boxing Drills', category: CATEGORIES.BOXING, level: 'Beginner', videoId: 'Ep_AeSLJbLc', bodyArea: BODY_AREAS.CARDIO, duration: 25 },
  { id: 9, title: 'Defensive Boxing Skills', category: CATEGORIES.BOXING, level: 'Intermediate', videoId: 'mvJHw64fxgQ', bodyArea: BODY_AREAS.FULL_BODY, duration: 30 },
  { id: 10, title: 'Counter-Punching Techniques', category: CATEGORIES.BOXING, level: 'Advanced', videoId: 'ml6cT4AZdqI', bodyArea: BODY_AREAS.UPPER_BODY, duration: 25 },
  { id: 11, title: 'Boxing Footwork Mastery', category: CATEGORIES.BOXING, level: 'Intermediate', videoId: 'KCAMp-7_qss', bodyArea: BODY_AREAS.LEGS, duration: 20 },
  { id: 12, title: 'Double End Bag Training', category: CATEGORIES.BOXING, level: 'Advanced', videoId: '2VK-9FZTsrg', bodyArea: BODY_AREAS.ARMS, duration: 18 },
  { id: 13, title: 'Slip & Roll Drills', category: CATEGORIES.BOXING, level: 'Intermediate', videoId: 'cZnsLVArIt8', bodyArea: BODY_AREAS.CORE, duration: 22 },
  { id: 14, title: 'Power Punching Workshop', category: CATEGORIES.BOXING, level: 'Advanced', videoId: 'EP2g3Sj3qSw', bodyArea: BODY_AREAS.FULL_BODY, duration: 35 },
  { id: 15, title: 'Boxing Cardio Blast', category: CATEGORIES.BOXING, level: 'Intermediate', videoId: 'R8xpN6Q5Gzk', bodyArea: BODY_AREAS.CARDIO, duration: 40 },
  { id: 16, title: 'Ring Movement & Positioning', category: CATEGORIES.BOXING, level: 'Advanced', videoId: 'SHgQeBk7zIs', bodyArea: BODY_AREAS.LEGS, duration: 28 },
  { id: 17, title: 'Combination Flow Training', category: CATEGORIES.BOXING, level: 'Intermediate', videoId: 'KlXv50C1eJo', bodyArea: BODY_AREAS.FULL_BODY, duration: 30 },
  { id: 18, title: 'Body Shot Mechanics', category: CATEGORIES.BOXING, level: 'Advanced', videoId: 'GBIIQ0kP15E', bodyArea: BODY_AREAS.CORE, duration: 25 },
  { id: 19, title: 'Boxing Reflex Training', category: CATEGORIES.BOXING, level: 'Intermediate', videoId: 'mzSsxYvSjKU', bodyArea: BODY_AREAS.UPPER_BODY, duration: 20 },
  { id: 20, title: 'Advanced Defensive Tactics', category: CATEGORIES.BOXING, level: 'Advanced', videoId: 'oL0OFLLyByg', bodyArea: BODY_AREAS.FULL_BODY, duration: 35 },
  { id: 21, title: 'Boxing Stamina Builder', category: CATEGORIES.BOXING, level: 'Beginner', videoId: 'E_6d3JBBo4s', bodyArea: BODY_AREAS.CARDIO, duration: 30 },
  { id: 22, title: 'Mitts & Pads Workout', category: CATEGORIES.BOXING, level: 'Intermediate', videoId: 'CYA7HM3YGho', bodyArea: BODY_AREAS.UPPER_BODY, duration: 25 },
  { id: 23, title: 'Speed & Agility Boxing', category: CATEGORIES.BOXING, level: 'Advanced', videoId: 'xW7VrJO6BPQ', bodyArea: BODY_AREAS.FULL_BODY, duration: 32 },
  { id: 24, title: 'Ring Craft Fundamentals', category: CATEGORIES.BOXING, level: 'Beginner', videoId: 'lS-vazd7x-M', bodyArea: BODY_AREAS.LEGS, duration: 18 },
  { id: 25, title: 'Pro Boxing Conditioning', category: CATEGORIES.BOXING, level: 'Advanced', videoId: 'VaKmECQHzBQ', bodyArea: BODY_AREAS.FULL_BODY, duration: 45 },

  // Kickboxing Exercises (25)
  { id: 26, title: 'Kickboxing Basics', category: CATEGORIES.KICKBOXING, level: 'Beginner', videoId: 'GBIIQ0kP15E', bodyArea: BODY_AREAS.FULL_BODY, duration: 20 },
  { id: 27, title: 'Power Kicks Training', category: CATEGORIES.KICKBOXING, level: 'Intermediate', videoId: 'mzSsxYvSjKU', bodyArea: BODY_AREAS.LEGS, duration: 25 },
  { id: 28, title: 'Kickboxing Cardio Blast', category: CATEGORIES.KICKBOXING, level: 'Intermediate', videoId: 'oL0OFLLyByg', bodyArea: BODY_AREAS.CARDIO, duration: 30 },
  { id: 29, title: 'Advanced Kickboxing Combos', category: CATEGORIES.KICKBOXING, level: 'Advanced', videoId: 'E_6d3JBBo4s', bodyArea: BODY_AREAS.FULL_BODY, duration: 35 },
  { id: 30, title: 'Roundhouse Kick Mastery', category: CATEGORIES.KICKBOXING, level: 'Intermediate', videoId: 'CYA7HM3YGho', bodyArea: BODY_AREAS.LEGS, duration: 22 },
  { id: 31, title: 'Front Kick Techniques', category: CATEGORIES.KICKBOXING, level: 'Beginner', videoId: 'xW7VrJO6BPQ', bodyArea: BODY_AREAS.LOWER_BODY, duration: 18 },
  { id: 32, title: 'Side Kick Training', category: CATEGORIES.KICKBOXING, level: 'Intermediate', videoId: 'lS-vazd7x-M', bodyArea: BODY_AREAS.LEGS, duration: 20 },
  { id: 33, title: 'Back Kick Drills', category: CATEGORIES.KICKBOXING, level: 'Advanced', videoId: 'VaKmECQHzBQ', bodyArea: BODY_AREAS.LOWER_BODY, duration: 25 },
  { id: 34, title: 'Spinning Techniques', category: CATEGORIES.KICKBOXING, level: 'Advanced', videoId: 'IODxDxX7oi4', bodyArea: BODY_AREAS.FULL_BODY, duration: 30 },
  { id: 35, title: 'Kickboxing Defense', category: CATEGORIES.KICKBOXING, level: 'Intermediate', videoId: 'eGo4IYlbE5g', bodyArea: BODY_AREAS.CORE, duration: 24 },
  { id: 36, title: 'Low Kick Conditioning', category: CATEGORIES.KICKBOXING, level: 'Beginner', videoId: 'Ep_AeSLJbLc', bodyArea: BODY_AREAS.LEGS, duration: 20 },
  { id: 37, title: 'High Kick Flexibility', category: CATEGORIES.KICKBOXING, level: 'Intermediate', videoId: 'mvJHw64fxgQ', bodyArea: BODY_AREAS.LOWER_BODY, duration: 26 },
  { id: 38, title: 'Punch-Kick Combinations', category: CATEGORIES.KICKBOXING, level: 'Advanced', videoId: 'ml6cT4AZdqI', bodyArea: BODY_AREAS.FULL_BODY, duration: 32 },
  { id: 39, title: 'Kickboxing Endurance', category: CATEGORIES.KICKBOXING, level: 'Intermediate', videoId: 'KCAMp-7_qss', bodyArea: BODY_AREAS.CARDIO, duration: 35 },
  { id: 40, title: 'Switch Kick Mastery', category: CATEGORIES.KICKBOXING, level: 'Advanced', videoId: '2VK-9FZTsrg', bodyArea: BODY_AREAS.LEGS, duration: 28 },
  { id: 41, title: 'Kickboxing Footwork', category: CATEGORIES.KICKBOXING, level: 'Beginner', videoId: 'cZnsLVArIt8', bodyArea: BODY_AREAS.LEGS, duration: 18 },
  { id: 42, title: 'Ring Control Kickboxing', category: CATEGORIES.KICKBOXING, level: 'Intermediate', videoId: 'EP2g3Sj3qSw', bodyArea: BODY_AREAS.FULL_BODY, duration: 30 },
  { id: 43, title: 'Jumping Kick Training', category: CATEGORIES.KICKBOXING, level: 'Advanced', videoId: 'R8xpN6Q5Gzk', bodyArea: BODY_AREAS.LEGS, duration: 27 },
  { id: 44, title: 'Kickboxing Conditioning Pro', category: CATEGORIES.KICKBOXING, level: 'Advanced', videoId: 'SHgQeBk7zIs', bodyArea: BODY_AREAS.FULL_BODY, duration: 40 },
  { id: 45, title: 'Speed Kicking Drills', category: CATEGORIES.KICKBOXING, level: 'Intermediate', videoId: 'KlXv50C1eJo', bodyArea: BODY_AREAS.LEGS, duration: 22 },
  { id: 46, title: 'Clinch Kickboxing', category: CATEGORIES.KICKBOXING, level: 'Advanced', videoId: 'dQw4w9WgXcQ', bodyArea: BODY_AREAS.UPPER_BODY, duration: 25 },
  { id: 47, title: 'Kickboxing Sparring Prep', category: CATEGORIES.KICKBOXING, level: 'Advanced', videoId: '3JZ_D3ELwOQ', bodyArea: BODY_AREAS.FULL_BODY, duration: 38 },
  { id: 48, title: 'Beginner Kickboxing Flow', category: CATEGORIES.KICKBOXING, level: 'Beginner', videoId: '2vjPBrBU-TM', bodyArea: BODY_AREAS.CARDIO, duration: 20 },
  { id: 49, title: 'Power & Precision Kicks', category: CATEGORIES.KICKBOXING, level: 'Intermediate', videoId: 'kJQP7kiw5Fk', bodyArea: BODY_AREAS.LEGS, duration: 28 },
  { id: 50, title: 'Elite Kickboxing Training', category: CATEGORIES.KICKBOXING, level: 'Advanced', videoId: 'ZZ5LpwO-An4', bodyArea: BODY_AREAS.FULL_BODY, duration: 45 },

  // Muay Thai Exercises (25)
  { id: 51, title: 'Muay Thai Fundamentals', category: CATEGORIES.MUAY_THAI, level: 'Beginner', videoId: 'CYA7HM3YGho', bodyArea: BODY_AREAS.FULL_BODY, duration: 25 },
  { id: 52, title: 'Clinch & Knee Training', category: CATEGORIES.MUAY_THAI, level: 'Intermediate', videoId: 'xW7VrJO6BPQ', bodyArea: BODY_AREAS.CORE, duration: 20 },
  { id: 53, title: 'Muay Thai Elbow Strikes', category: CATEGORIES.MUAY_THAI, level: 'Intermediate', videoId: 'lS-vazd7x-M', bodyArea: BODY_AREAS.ARMS, duration: 15 },
  { id: 54, title: 'Muay Thai Fight Conditioning', category: CATEGORIES.MUAY_THAI, level: 'Advanced', videoId: 'VaKmECQHzBQ', bodyArea: BODY_AREAS.FULL_BODY, duration: 40 },
  { id: 55, title: 'Teep (Push Kick) Mastery', category: CATEGORIES.MUAY_THAI, level: 'Beginner', videoId: 'IODxDxX7oi4', bodyArea: BODY_AREAS.LEGS, duration: 18 },
  { id: 56, title: 'Thai Pad Combinations', category: CATEGORIES.MUAY_THAI, level: 'Intermediate', videoId: 'eGo4IYlbE5g', bodyArea: BODY_AREAS.FULL_BODY, duration: 30 },
  { id: 57, title: 'Low Kick Techniques', category: CATEGORIES.MUAY_THAI, level: 'Beginner', videoId: 'Ep_AeSLJbLc', bodyArea: BODY_AREAS.LEGS, duration: 20 },
  { id: 58, title: 'Muay Thai Clinch Work', category: CATEGORIES.MUAY_THAI, level: 'Advanced', videoId: 'mvJHw64fxgQ', bodyArea: BODY_AREAS.UPPER_BODY, duration: 28 },
  { id: 59, title: 'Knee Strike Variations', category: CATEGORIES.MUAY_THAI, level: 'Intermediate', videoId: 'ml6cT4AZdqI', bodyArea: BODY_AREAS.CORE, duration: 22 },
  { id: 60, title: 'Elbow Combinations', category: CATEGORIES.MUAY_THAI, level: 'Advanced', videoId: 'KCAMp-7_qss', bodyArea: BODY_AREAS.ARMS, duration: 18 },
  { id: 61, title: 'Muay Thai Bag Work', category: CATEGORIES.MUAY_THAI, level: 'Intermediate', videoId: '2VK-9FZTsrg', bodyArea: BODY_AREAS.FULL_BODY, duration: 32 },
  { id: 62, title: 'Defensive Muay Thai', category: CATEGORIES.MUAY_THAI, level: 'Advanced', videoId: 'cZnsLVArIt8', bodyArea: BODY_AREAS.CORE, duration: 26 },
  { id: 63, title: 'Thai Boxing Cardio', category: CATEGORIES.MUAY_THAI, level: 'Beginner', videoId: 'EP2g3Sj3qSw', bodyArea: BODY_AREAS.CARDIO, duration: 25 },
  { id: 64, title: 'Spinning Elbow Drills', category: CATEGORIES.MUAY_THAI, level: 'Advanced', videoId: 'R8xpN6Q5Gzk', bodyArea: BODY_AREAS.UPPER_BODY, duration: 20 },
  { id: 65, title: 'Flying Knee Techniques', category: CATEGORIES.MUAY_THAI, level: 'Advanced', videoId: 'SHgQeBk7zIs', bodyArea: BODY_AREAS.FULL_BODY, duration: 24 },
  { id: 66, title: 'Muay Thai Shadow Work', category: CATEGORIES.MUAY_THAI, level: 'Beginner', videoId: 'KlXv50C1eJo', bodyArea: BODY_AREAS.CARDIO, duration: 22 },
  { id: 67, title: 'Switch Kick Mastery', category: CATEGORIES.MUAY_THAI, level: 'Intermediate', videoId: 'GBIIQ0kP15E', bodyArea: BODY_AREAS.LEGS, duration: 24 },
  { id: 68, title: 'Muay Thai Conditioning', category: CATEGORIES.MUAY_THAI, level: 'Advanced', videoId: 'mzSsxYvSjKU', bodyArea: BODY_AREAS.FULL_BODY, duration: 38 },
  { id: 69, title: 'Clinch Knee Combinations', category: CATEGORIES.MUAY_THAI, level: 'Intermediate', videoId: 'oL0OFLLyByg', bodyArea: BODY_AREAS.CORE, duration: 26 },
  { id: 70, title: 'Muay Thai Ring Control', category: CATEGORIES.MUAY_THAI, level: 'Advanced', videoId: 'E_6d3JBBo4s', bodyArea: BODY_AREAS.LEGS, duration: 30 },
  { id: 71, title: 'Roundhouse Power Training', category: CATEGORIES.MUAY_THAI, level: 'Intermediate', videoId: 'CYA7HM3YGho', bodyArea: BODY_AREAS.LEGS, duration: 28 },
  { id: 72, title: 'Muay Thai Sparring Prep', category: CATEGORIES.MUAY_THAI, level: 'Advanced', videoId: 'xW7VrJO6BPQ', bodyArea: BODY_AREAS.FULL_BODY, duration: 35 },
  { id: 73, title: 'Thai Boxing Basics', category: CATEGORIES.MUAY_THAI, level: 'Beginner', videoId: 'lS-vazd7x-M', bodyArea: BODY_AREAS.FULL_BODY, duration: 20 },
  { id: 74, title: 'Advanced Clinch Tactics', category: CATEGORIES.MUAY_THAI, level: 'Advanced', videoId: 'VaKmECQHzBQ', bodyArea: BODY_AREAS.UPPER_BODY, duration: 32 },
  { id: 75, title: 'Muay Thai Fighter Training', category: CATEGORIES.MUAY_THAI, level: 'Advanced', videoId: 'IODxDxX7oi4', bodyArea: BODY_AREAS.FULL_BODY, duration: 45 },

  // Calisthenics Exercises (25)
  { id: 76, title: 'Push-Up Variations', category: CATEGORIES.CALISTHENICS, level: 'Beginner', videoId: 'IODxDxX7oi4', bodyArea: BODY_AREAS.CHEST, duration: 15 },
  { id: 77, title: 'Pull-Up Progressions', category: CATEGORIES.CALISTHENICS, level: 'Intermediate', videoId: 'eGo4IYlbE5g', bodyArea: BODY_AREAS.BACK, duration: 20 },
  { id: 78, title: 'Core Calisthenics', category: CATEGORIES.CALISTHENICS, level: 'Intermediate', videoId: 'Ep_AeSLJbLc', bodyArea: BODY_AREAS.CORE, duration: 18 },
  { id: 79, title: 'Advanced Calisthenics Routine', category: CATEGORIES.CALISTHENICS, level: 'Advanced', videoId: 'mvJHw64fxgQ', bodyArea: BODY_AREAS.FULL_BODY, duration: 30 },
  { id: 80, title: 'Dip Progressions', category: CATEGORIES.CALISTHENICS, level: 'Intermediate', videoId: 'ml6cT4AZdqI', bodyArea: BODY_AREAS.CHEST, duration: 18 },
  { id: 81, title: 'Bodyweight Squat Mastery', category: CATEGORIES.CALISTHENICS, level: 'Beginner', videoId: 'KCAMp-7_qss', bodyArea: BODY_AREAS.LEGS, duration: 20 },
  { id: 82, title: 'Plank Variations', category: CATEGORIES.CALISTHENICS, level: 'Beginner', videoId: '2VK-9FZTsrg', bodyArea: BODY_AREAS.CORE, duration: 15 },
  { id: 83, title: 'Handstand Progressions', category: CATEGORIES.CALISTHENICS, level: 'Advanced', videoId: 'cZnsLVArIt8', bodyArea: BODY_AREAS.SHOULDERS, duration: 25 },
  { id: 84, title: 'Muscle-Up Training', category: CATEGORIES.CALISTHENICS, level: 'Advanced', videoId: 'EP2g3Sj3qSw', bodyArea: BODY_AREAS.UPPER_BODY, duration: 28 },
  { id: 85, title: 'Lunge Variations', category: CATEGORIES.CALISTHENICS, level: 'Beginner', videoId: 'R8xpN6Q5Gzk', bodyArea: BODY_AREAS.LEGS, duration: 18 },
  { id: 86, title: 'Burpee Progressions', category: CATEGORIES.CALISTHENICS, level: 'Intermediate', videoId: 'SHgQeBk7zIs', bodyArea: BODY_AREAS.FULL_BODY, duration: 22 },
  { id: 87, title: 'Front Lever Training', category: CATEGORIES.CALISTHENICS, level: 'Advanced', videoId: 'KlXv50C1eJo', bodyArea: BODY_AREAS.CORE, duration: 24 },
  { id: 88, title: 'Back Lever Progressions', category: CATEGORIES.CALISTHENICS, level: 'Advanced', videoId: 'GBIIQ0kP15E', bodyArea: BODY_AREAS.BACK, duration: 26 },
  { id: 89, title: 'L-Sit Training', category: CATEGORIES.CALISTHENICS, level: 'Intermediate', videoId: 'mzSsxYvSjKU', bodyArea: BODY_AREAS.CORE, duration: 20 },
  { id: 90, title: 'Human Flag Progressions', category: CATEGORIES.CALISTHENICS, level: 'Advanced', videoId: 'oL0OFLLyByg', bodyArea: BODY_AREAS.FULL_BODY, duration: 30 },
  { id: 91, title: 'Pistol Squat Training', category: CATEGORIES.CALISTHENICS, level: 'Advanced', videoId: 'E_6d3JBBo4s', bodyArea: BODY_AREAS.LEGS, duration: 22 },
  { id: 92, title: 'Mountain Climbers', category: CATEGORIES.CALISTHENICS, level: 'Beginner', videoId: 'CYA7HM3YGho', bodyArea: BODY_AREAS.CARDIO, duration: 15 },
  { id: 93, title: 'Calisthenics Flow Routine', category: CATEGORIES.CALISTHENICS, level: 'Intermediate', videoId: 'xW7VrJO6BPQ', bodyArea: BODY_AREAS.FULL_BODY, duration: 28 },
  { id: 94, title: 'Explosive Push-Ups', category: CATEGORIES.CALISTHENICS, level: 'Advanced', videoId: 'lS-vazd7x-M', bodyArea: BODY_AREAS.CHEST, duration: 18 },
  { id: 95, title: 'Hanging Leg Raises', category: CATEGORIES.CALISTHENICS, level: 'Intermediate', videoId: 'VaKmECQHzBQ', bodyArea: BODY_AREAS.CORE, duration: 16 },
  { id: 96, title: 'Bar Muscle-Up Skills', category: CATEGORIES.CALISTHENICS, level: 'Advanced', videoId: 'IODxDxX7oi4', bodyArea: BODY_AREAS.UPPER_BODY, duration: 25 },
  { id: 97, title: 'Bodyweight Conditioning', category: CATEGORIES.CALISTHENICS, level: 'Intermediate', videoId: 'eGo4IYlbE5g', bodyArea: BODY_AREAS.FULL_BODY, duration: 32 },
  { id: 98, title: 'Street Workout Basics', category: CATEGORIES.CALISTHENICS, level: 'Beginner', videoId: 'Ep_AeSLJbLc', bodyArea: BODY_AREAS.FULL_BODY, duration: 20 },
  { id: 99, title: 'Calisthenics Strength Build', category: CATEGORIES.CALISTHENICS, level: 'Advanced', videoId: 'mvJHw64fxgQ', bodyArea: BODY_AREAS.FULL_BODY, duration: 35 },
  { id: 100, title: 'Dynamic Calisthenics', category: CATEGORIES.CALISTHENICS, level: 'Advanced', videoId: 'ml6cT4AZdqI', bodyArea: BODY_AREAS.FULL_BODY, duration: 40 },

  // HIIT Exercises (25)
  { id: 101, title: 'HIIT for Beginners', category: CATEGORIES.HIIT, level: 'Beginner', videoId: 'ml6cT4AZdqI', bodyArea: BODY_AREAS.FULL_BODY, duration: 20 },
  { id: 102, title: 'Tabata Training', category: CATEGORIES.HIIT, level: 'Intermediate', videoId: 'KCAMp-7_qss', bodyArea: BODY_AREAS.CARDIO, duration: 25 },
  { id: 103, title: 'HIIT Leg Burner', category: CATEGORIES.HIIT, level: 'Intermediate', videoId: '2VK-9FZTsrg', bodyArea: BODY_AREAS.LEGS, duration: 22 },
  { id: 104, title: 'Extreme HIIT Challenge', category: CATEGORIES.HIIT, level: 'Advanced', videoId: 'cZnsLVArIt8', bodyArea: BODY_AREAS.FULL_BODY, duration: 35 },
  { id: 105, title: 'Jumping HIIT Workout', category: CATEGORIES.HIIT, level: 'Intermediate', videoId: 'EP2g3Sj3qSw', bodyArea: BODY_AREAS.CARDIO, duration: 24 },
  { id: 106, title: 'Core HIIT Blast', category: CATEGORIES.HIIT, level: 'Beginner', videoId: 'R8xpN6Q5Gzk', bodyArea: BODY_AREAS.CORE, duration: 18 },
  { id: 107, title: 'Upper Body HIIT', category: CATEGORIES.HIIT, level: 'Intermediate', videoId: 'SHgQeBk7zIs', bodyArea: BODY_AREAS.UPPER_BODY, duration: 26 },
  { id: 108, title: 'Full Body HIIT Burn', category: CATEGORIES.HIIT, level: 'Advanced', videoId: 'KlXv50C1eJo', bodyArea: BODY_AREAS.FULL_BODY, duration: 30 },
  { id: 109, title: 'Sprint Interval Training', category: CATEGORIES.HIIT, level: 'Advanced', videoId: 'GBIIQ0kP15E', bodyArea: BODY_AREAS.CARDIO, duration: 28 },
  { id: 110, title: 'Plyometric HIIT', category: CATEGORIES.HIIT, level: 'Advanced', videoId: 'mzSsxYvSjKU', bodyArea: BODY_AREAS.LEGS, duration: 32 },
  { id: 111, title: 'Beginner Cardio HIIT', category: CATEGORIES.HIIT, level: 'Beginner', videoId: 'oL0OFLLyByg', bodyArea: BODY_AREAS.CARDIO, duration: 15 },
  { id: 112, title: 'Kettlebell HIIT', category: CATEGORIES.HIIT, level: 'Intermediate', videoId: 'E_6d3JBBo4s', bodyArea: BODY_AREAS.FULL_BODY, duration: 28 },
  { id: 113, title: 'Battle Rope HIIT', category: CATEGORIES.HIIT, level: 'Advanced', videoId: 'CYA7HM3YGho', bodyArea: BODY_AREAS.UPPER_BODY, duration: 20 },
  { id: 114, title: 'Box Jump HIIT', category: CATEGORIES.HIIT, level: 'Intermediate', videoId: 'xW7VrJO6BPQ', bodyArea: BODY_AREAS.LEGS, duration: 22 },
  { id: 115, title: 'Burpee HIIT Challenge', category: CATEGORIES.HIIT, level: 'Advanced', videoId: 'lS-vazd7x-M', bodyArea: BODY_AREAS.FULL_BODY, duration: 25 },
  { id: 116, title: 'Cardio Blast HIIT', category: CATEGORIES.HIIT, level: 'Beginner', videoId: 'VaKmECQHzBQ', bodyArea: BODY_AREAS.CARDIO, duration: 20 },
  { id: 117, title: 'Athletic HIIT Training', category: CATEGORIES.HIIT, level: 'Advanced', videoId: 'IODxDxX7oi4', bodyArea: BODY_AREAS.FULL_BODY, duration: 34 },
  { id: 118, title: 'Lower Body HIIT', category: CATEGORIES.HIIT, level: 'Intermediate', videoId: 'eGo4IYlbE5g', bodyArea: BODY_AREAS.LEGS, duration: 26 },
  { id: 119, title: 'HIIT & Core', category: CATEGORIES.HIIT, level: 'Intermediate', videoId: 'Ep_AeSLJbLc', bodyArea: BODY_AREAS.CORE, duration: 24 },
  { id: 120, title: 'Fat Burning HIIT', category: CATEGORIES.HIIT, level: 'Beginner', videoId: 'mvJHw64fxgQ', bodyArea: BODY_AREAS.CARDIO, duration: 22 },
  { id: 121, title: 'Advanced Tabata', category: CATEGORIES.HIIT, level: 'Advanced', videoId: 'ml6cT4AZdqI', bodyArea: BODY_AREAS.FULL_BODY, duration: 30 },
  { id: 122, title: 'HIIT Metabolic Boost', category: CATEGORIES.HIIT, level: 'Intermediate', videoId: 'KCAMp-7_qss', bodyArea: BODY_AREAS.CARDIO, duration: 28 },
  { id: 123, title: 'Power HIIT Workout', category: CATEGORIES.HIIT, level: 'Advanced', videoId: '2VK-9FZTsrg', bodyArea: BODY_AREAS.FULL_BODY, duration: 36 },
  { id: 124, title: 'Quick HIIT Session', category: CATEGORIES.HIIT, level: 'Beginner', videoId: 'cZnsLVArIt8', bodyArea: BODY_AREAS.FULL_BODY, duration: 15 },
  { id: 125, title: 'Elite HIIT Training', category: CATEGORIES.HIIT, level: 'Advanced', videoId: 'EP2g3Sj3qSw', bodyArea: BODY_AREAS.FULL_BODY, duration: 40 },

  // Weightlifting Exercises (25)
  { id: 126, title: 'Compound Lifts Basics', category: CATEGORIES.WEIGHTLIFTING, level: 'Beginner', videoId: 'EP2g3Sj3qSw', bodyArea: BODY_AREAS.FULL_BODY, duration: 30 },
  { id: 127, title: 'Upper Body Strength', category: CATEGORIES.WEIGHTLIFTING, level: 'Intermediate', videoId: 'R8xpN6Q5Gzk', bodyArea: BODY_AREAS.UPPER_BODY, duration: 35 },
  { id: 128, title: 'Leg Day Power', category: CATEGORIES.WEIGHTLIFTING, level: 'Intermediate', videoId: 'SHgQeBk7zIs', bodyArea: BODY_AREAS.LEGS, duration: 40 },
  { id: 129, title: 'Olympic Lifting Techniques', category: CATEGORIES.WEIGHTLIFTING, level: 'Advanced', videoId: 'KlXv50C1eJo', bodyArea: BODY_AREAS.FULL_BODY, duration: 45 },
  { id: 130, title: 'Squat Mastery', category: CATEGORIES.WEIGHTLIFTING, level: 'Intermediate', videoId: 'GBIIQ0kP15E', bodyArea: BODY_AREAS.LEGS, duration: 35 },
  { id: 131, title: 'Deadlift Fundamentals', category: CATEGORIES.WEIGHTLIFTING, level: 'Beginner', videoId: 'mzSsxYvSjKU', bodyArea: BODY_AREAS.BACK, duration: 30 },
  { id: 132, title: 'Bench Press Training', category: CATEGORIES.WEIGHTLIFTING, level: 'Intermediate', videoId: 'oL0OFLLyByg', bodyArea: BODY_AREAS.CHEST, duration: 32 },
  { id: 133, title: 'Overhead Press Power', category: CATEGORIES.WEIGHTLIFTING, level: 'Advanced', videoId: 'E_6d3JBBo4s', bodyArea: BODY_AREAS.SHOULDERS, duration: 28 },
  { id: 134, title: 'Power Clean Training', category: CATEGORIES.WEIGHTLIFTING, level: 'Advanced', videoId: 'CYA7HM3YGho', bodyArea: BODY_AREAS.FULL_BODY, duration: 38 },
  { id: 135, title: 'Front Squat Technique', category: CATEGORIES.WEIGHTLIFTING, level: 'Intermediate', videoId: 'xW7VrJO6BPQ', bodyArea: BODY_AREAS.LEGS, duration: 34 },
  { id: 136, title: 'Romanian Deadlifts', category: CATEGORIES.WEIGHTLIFTING, level: 'Intermediate', videoId: 'lS-vazd7x-M', bodyArea: BODY_AREAS.LOWER_BODY, duration: 30 },
  { id: 137, title: 'Barbell Row Mastery', category: CATEGORIES.WEIGHTLIFTING, level: 'Beginner', videoId: 'VaKmECQHzBQ', bodyArea: BODY_AREAS.BACK, duration: 25 },
  { id: 138, title: 'Clean & Jerk', category: CATEGORIES.WEIGHTLIFTING, level: 'Advanced', videoId: 'IODxDxX7oi4', bodyArea: BODY_AREAS.FULL_BODY, duration: 42 },
  { id: 139, title: 'Snatch Training', category: CATEGORIES.WEIGHTLIFTING, level: 'Advanced', videoId: 'eGo4IYlbE5g', bodyArea: BODY_AREAS.FULL_BODY, duration: 40 },
  { id: 140, title: 'Dumbbell Strength', category: CATEGORIES.WEIGHTLIFTING, level: 'Beginner', videoId: 'Ep_AeSLJbLc', bodyArea: BODY_AREAS.UPPER_BODY, duration: 28 },
  { id: 141, title: 'Back Squat Pro', category: CATEGORIES.WEIGHTLIFTING, level: 'Advanced', videoId: 'mvJHw64fxgQ', bodyArea: BODY_AREAS.LEGS, duration: 38 },
  { id: 142, title: 'Incline Press', category: CATEGORIES.WEIGHTLIFTING, level: 'Intermediate', videoId: 'ml6cT4AZdqI', bodyArea: BODY_AREAS.CHEST, duration: 30 },
  { id: 143, title: 'Sumo Deadlift', category: CATEGORIES.WEIGHTLIFTING, level: 'Intermediate', videoId: 'KCAMp-7_qss', bodyArea: BODY_AREAS.LEGS, duration: 32 },
  { id: 144, title: 'Push Press Power', category: CATEGORIES.WEIGHTLIFTING, level: 'Advanced', videoId: '2VK-9FZTsrg', bodyArea: BODY_AREAS.SHOULDERS, duration: 30 },
  { id: 145, title: 'Trap Bar Deadlift', category: CATEGORIES.WEIGHTLIFTING, level: 'Beginner', videoId: 'cZnsLVArIt8', bodyArea: BODY_AREAS.FULL_BODY, duration: 26 },
  { id: 146, title: 'Weightlifting Conditioning', category: CATEGORIES.WEIGHTLIFTING, level: 'Advanced', videoId: 'EP2g3Sj3qSw', bodyArea: BODY_AREAS.FULL_BODY, duration: 45 },
  { id: 147, title: 'Strength Hypertrophy', category: CATEGORIES.WEIGHTLIFTING, level: 'Intermediate', videoId: 'R8xpN6Q5Gzk', bodyArea: BODY_AREAS.FULL_BODY, duration: 40 },
  { id: 148, title: 'Power Building Routine', category: CATEGORIES.WEIGHTLIFTING, level: 'Advanced', videoId: 'SHgQeBk7zIs', bodyArea: BODY_AREAS.FULL_BODY, duration: 50 },
  { id: 149, title: 'Beginner Barbell Training', category: CATEGORIES.WEIGHTLIFTING, level: 'Beginner', videoId: 'KlXv50C1eJo', bodyArea: BODY_AREAS.FULL_BODY, duration: 30 },
  { id: 150, title: 'Elite Powerlifting', category: CATEGORIES.WEIGHTLIFTING, level: 'Advanced', videoId: 'GBIIQ0kP15E', bodyArea: BODY_AREAS.FULL_BODY, duration: 55 }
];

// Get workouts by category
export const getWorkoutsByCategory = (category) => {
  return workoutData.filter(workout => workout.category === category);
};

// Get workouts by level
export const getWorkoutsByLevel = (level) => {
  return workoutData.filter(workout => workout.level === level);
};

// Get workouts by body area
export const getWorkoutsByBodyArea = (bodyArea) => {
  return workoutData.filter(workout => workout.bodyArea === bodyArea);
};
